# Site settings
title: 凯锅V5 
author: kai
header-img: img/home-bg.jpg
email: 34034537@qq.com
copyright_name: zongkai
description: "Just for fun"
#baseurl: "/startbootstrap-clean-blog-jekyll"
url: "http://www.blog.zkv5.com"
qq_username: 34034537 
github_username: zongkaizhang 
weixin_username:  IronSummitMedia
email_username:  34034537@qq.com

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
